# Generated by Django 5.1.7 on 2026-07-21 16:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tenancy', '0003_alter_client_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('needs_rebuild', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.client')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('content_markdown', models.TextField(help_text='Escreva em Markdown. Será renderizado em HTML no site.')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('is_home', models.BooleanField(default=False, help_text='Marque para ser a página inicial')),
                ('order', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.project')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug', 'is_published'], name='core_projec_slug_c7ef1a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['needs_rebuild'], name='core_projec_needs_r_8a90e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('client', 'slug'), name='unique_project_slug_per_client'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['project', 'is_published'], name='core_page_project_7a0848_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug', 'is_published'], name='core_page_slug_a598aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_page_slug_per_project'),
        ),
    ]
