# Generated by Django 5.1.7 on 2026-07-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_page_project_core_projec_slug_c7ef1a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content_markdown',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default='', help_text='Conteúdo em Markdown ou HTML (conforme o formato selecionado)'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_format',
            field=models.CharField(choices=[('markdown', '📝 Markdown (Recomendado - Seguro & Rápido)'), ('html_safe', '🔒 HTML Seguro (HTML + CSS, sem JavaScript)'), ('html_custom', '⚡ HTML Customizado (HTML + CSS + JavaScript via iFrame)')], default='markdown', help_text='Escolha como você quer criar o conteúdo', max_length=20),
        ),
    ]
