# Generated by Django 5.1.7 on 2026-07-22 20:34

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_page_content_markdown_page_content_and_more'),
        ('tenancy', '0003_alter_client_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('success', 'Sucesso'), ('failed', 'Falha')], default='pending', max_length=20)),
                ('log_output', models.TextField(blank=True, help_text='stdout + stderr do build')),
                ('content_snapshot', models.JSONField(default=list, help_text='Snapshot das páginas no momento do build')),
                ('release_path', models.CharField(blank=True, help_text='ex: releases/20260722-153000', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.client')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Build',
                'verbose_name_plural': 'Builds',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('deploying', 'Deployando'), ('success', 'Sucesso'), ('failed', 'Falha'), ('rolled_back', 'Revertido')], default='pending', max_length=20)),
                ('log_output', models.TextField(blank=True, help_text='stdout + stderr do deploy')),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('build', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment', to='core.build')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.client')),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['status', 'created'], name='core_build_status_a647f5_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['status', 'created'], name='core_deploy_status_622cd3_idx'),
        ),
    ]
