# Generated by Django 5.1.7 on 2026-07-22 20:44

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_build_deployment_build_core_build_status_a647f5_idx_and_more'),
        ('tenancy', '0003_alter_client_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('domain', models.CharField(help_text='ex: agenciafuturo.com.br', max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Se True, é o domínio padrão; False = domínio customizado')),
                ('verification_status', models.CharField(choices=[('pending_dns', 'Pendente DNS'), ('dns_verified', 'DNS Verificado'), ('failed', 'Falha na Verificação')], default='pending_dns', help_text='Status da verificação de DNS', max_length=20)),
                ('ssl_status', models.CharField(choices=[('none', 'Nenhum'), ('pending', 'Pendente'), ('issued', 'Ativo'), ('failed', 'Falha')], default='none', help_text='Status do certificado SSL', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp da verificação', null=True)),
                ('dns_check_log', models.TextField(blank=True, help_text='Log da última verificação de DNS')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.client')),
                ('project', models.ForeignKey(help_text='Projeto associado', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.project')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['domain'],
                'indexes': [models.Index(fields=['project', 'is_primary'], name='core_domain_project_7154dd_idx'), models.Index(fields=['verification_status', 'ssl_status'], name='core_domain_verific_a388d7_idx')],
            },
        ),
    ]
