# Generated by Django 5.1.7 on 2026-07-22 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_domain'),
        ('tenancy', '0003_alter_client_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='project',
            field=models.ForeignKey(default=1, help_text='Projeto que este build gerou (build é sempre escopado a 1 projeto)', on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='core.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='build',
            name='content_snapshot',
            field=models.JSONField(default=list, help_text='Snapshot das páginas do projeto no momento do build'),
        ),
        migrations.AlterField(
            model_name='build',
            name='release_path',
            field=models.CharField(blank=True, help_text='ex: releases/20260722-153000 (preenchido no deploy, não no build)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['project', 'created'], name='core_build_project_174c2d_idx'),
        ),
    ]
