# Generated by Django 5.1.7 on 2026-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_build_project_alter_build_content_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='marketing_opt_in',
            field=models.BooleanField(default=False, help_text='Aceitou receber dicas/atualizações por email no cadastro'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
