# Generated by Django 5.1.7 on 2026-07-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clientuser_marketing_opt_in_clientuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['domain'], 'verbose_name': 'Meu Domínio', 'verbose_name_plural': 'Meus Domínios'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Minha Página', 'verbose_name_plural': 'Minhas Páginas'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Meu Projeto', 'verbose_name_plural': 'Meus Projetos'},
        ),
    ]
