# Generated by Django 5.1.7 on 2026-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_domain_options_alter_page_options_and_more'),
        ('tenancy', '0003_alter_client_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('is_home', True)), fields=('project',), name='unique_home_page_per_project'),
        ),
    ]
