# Generated by Django 5.1.7 on 2026-07-23 22:45, hand-edited to preserve
# Page.seo_title/seo_description data by moving it into PageSeoSettings
# before the old columns are dropped, and to backfill Project/PageSeoSettings
# rows for records that already existed before this migration (the
# post_save signal that auto-creates them only fires on creation).

import django.db.models.deletion
from django.db import migrations, models


def copy_seo_data_and_backfill(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Page = apps.get_model('core', 'Page')
    ProjectSeoSettings = apps.get_model('core', 'ProjectSeoSettings')
    PageSeoSettings = apps.get_model('core', 'PageSeoSettings')

    ProjectSeoSettings.objects.bulk_create(
        [ProjectSeoSettings(project=project) for project in Project.objects.all()],
        ignore_conflicts=True,
    )
    PageSeoSettings.objects.bulk_create(
        [
            PageSeoSettings(
                page=page,
                seo_title=page.seo_title,
                seo_description=page.seo_description,
            )
            for page in Page.objects.all()
        ],
        ignore_conflicts=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_page_unique_home_page_per_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSeoDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('default_favicon_url', models.URLField(blank=True)),
                ('default_og_image_url', models.URLField(blank=True)),
                ('default_author_name', models.CharField(blank=True, max_length=255)),
                ('theme_color', models.CharField(blank=True, help_text='ex: #0f172a', max_length=7)),
                ('google_site_verification', models.CharField(blank=True, max_length=255)),
                ('gtm_id', models.CharField(blank=True, max_length=32)),
                ('locale', models.CharField(default='pt-BR', max_length=10)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('organization_logo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuração de SEO da Plataforma',
                'verbose_name_plural': 'Configuração de SEO da Plataforma',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Página Inicial'), ('generic', 'Genérica'), ('contact', 'Contato'), ('about', 'Sobre'), ('blog_post', 'Post de Blog'), ('landing', 'Landing Page')], default='generic', help_text='Tipo de conteúdo — habilita campos de SEO específicos (ex: endereço em Contato)', max_length=20),
        ),
        migrations.CreateModel(
            name='PageSeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('og_image_override', models.URLField(blank=True)),
                ('canonical_override', models.URLField(blank=True)),
                ('noindex', models.BooleanField(default=False, help_text='Pede aos buscadores para não indexar esta página')),
                ('type_specific_data', models.JSONField(blank=True, default=dict, help_text='Campos extras conforme page_type (ex: endereço, telefone, data de publicação)')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='core.page')),
            ],
            options={
                'verbose_name': 'SEO da Página',
                'verbose_name_plural': 'SEO das Páginas',
            },
        ),
        migrations.CreateModel(
            name='ProjectSeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_image_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('canonical_domain_override', models.CharField(blank=True, help_text='Reservado para domínio customizado (feature futura)', max_length=255)),
                ('organization_name_override', models.CharField(blank=True, max_length=255)),
                ('default_title_suffix', models.CharField(blank=True, help_text='ex: " | Minha Empresa" — anexado ao título quando a página não definir o próprio', max_length=100)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='core.project')),
            ],
            options={
                'verbose_name': 'SEO do Projeto',
                'verbose_name_plural': 'SEO dos Projetos',
            },
        ),
        migrations.RunPython(copy_seo_data_and_backfill, noop_reverse),
        migrations.RemoveField(
            model_name='page',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_title',
        ),
    ]
