# Generated by Django 5.1.7 on 2026-07-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seo_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Página Inicial'), ('generic', 'Genérica'), ('contact', 'Contato'), ('about', 'Sobre'), ('blog_post', 'Post de Blog'), ('landing', 'Landing Page'), ('faq', 'FAQ'), ('person', 'Pessoa/Perfil'), ('product', 'Produto'), ('article', 'Artigo')], default='generic', help_text='Tipo de conteúdo — habilita campos de SEO específicos (ex: endereço em Contato)', max_length=20),
        ),
    ]
