# Generated by Django 5.1.7 on 2026-07-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_page_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectseosettings',
            name='llms_summary',
            field=models.CharField(blank=True, help_text='Descrição curta do projeto pro /llms.txt — se vazio, cai pra seo_description da home page', max_length=300),
        ),
    ]
