# Generated by Django 5.1.7 on 2026-07-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_projectseosettings_llms_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='blocks',
            field=models.JSONField(blank=True, default=dict, help_text='Documento de blocos (formato Puck).'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default='', help_text='[legado] Conteúdo em blob. Use o campo `blocks`.'),
        ),
    ]
