# Generated by Django 5.1.7 on 2026-07-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_page_blocks_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chrome',
            field=models.JSONField(blank=True, default=dict, help_text='Header/Footer de nível de Site. Ver chrome/chrome.ts.'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.JSONField(blank=True, default=dict, help_text='Tokens de tema (cores/fontes/radius). Ver theme/theme.ts.'),
        ),
    ]
