# Generated by Django 5.1.7 on 2026-07-25 02:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_project_chrome_project_theme'),
        ('tenancy', '0003_alter_client_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('niche', models.CharField(blank=True, help_text='Nicho do template (ex: Advocacia, Odontologia).', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_official', models.BooleanField(default=False, help_text='Oficial = catálogo global da plataforma (sem dono). Marque só via staff.')),
                ('snapshot', models.JSONField(default=dict)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Imagem de preview (opcional; geração automática é fase futura).')),
                ('owner_client', models.ForeignKey(blank=True, help_text='Dono do template privado. Vazio = template oficial/global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='tenancy.client')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-is_official', 'name'],
            },
        ),
    ]
