# Generated by Django 5.1.7 on 2026-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='kind',
            field=models.CharField(choices=[('site', 'Site (projeto inteiro)'), ('page', 'Página')], default='site', help_text='Site = instancia um projeto novo. Página = adiciona 1 página a um projeto.', max_length=10),
        ),
    ]
