# Generated by Django 5.1.7 on 2026-07-28 10:55

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_template_kind'),
        ('tenancy', '0003_alter_client_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('upload', 'Upload'), ('stock', 'Stock'), ('url', 'URL externa'), ('adjusted', 'Ajustado')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.client')),
                ('project', models.ForeignKey(blank=True, help_text='Projeto de origem do upload (denormalizado, não filtra a galeria).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Galeria de Imagens',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['client', '-created'], name='core_mediaa_client__72baaa_idx')],
            },
        ),
    ]
