/**
 * 🚨 AUTO-GENERATED FILE. DO NOT EDIT.
 * This file is generated by sync-blog.js and will be overwritten.
 * To customize, edit the template.
 */

// this's done on purpose to get the respective siteid site-config.ts customized by the user.
import { siteConfig as siteConfigType } from '../site-config.ts';

type SiteConfig = typeof siteConfigType;
// Helper functions for the new nested siteConfig structure
export class SiteConfigHelper {
    /**
     * Dynamically load site config for Astro components
     * Uses SITE_ID environment variable or falls back to fastvistos
     */
    static async loadSiteConfig() {
        const siteId = 'revistadoturismo';
        try {
            const module = await import('../site-config.ts');
            return module.siteConfig;
        } catch (error) {
            console.warn(`Could not load site config for ${siteId}, falling back to fastvistos`);
            const fallback = await import('../site-config.ts');
            return fallback.siteConfig;
        }
    }

    static getMetadata(config: SiteConfig, pageTitle?: string, pageDescription?: string) {
        // Support both flat and nested config structures
        const seo =
            (config as any).seo ||
            (config as any).homePageConfig?.seo ||
            (config as any).blogPageConfig?.seo ||
            {};
        const business = (config as any).business || config;
        return {
            title: pageTitle ? `${pageTitle} | ${business.name ?? ''}` : seo.title,
            description: pageDescription || seo.description,
            keywords: Array.isArray(seo.keywords) ? seo.keywords.join(', ') : '',
            ogImage: seo.ogImage,
            siteName: business.name ?? '',
            domain: business.domain ?? '',
            language: business.language ?? '',
        };
    }

    static getCssVariables(config: SiteConfig): Record<string, string> {
        const branding = config.branding || {};
        return {
            '--primary-color': branding.primaryColor,
            '--secondary-color': branding.secondaryColor,
            ...((config.customStyles && config.customStyles.cssVars) || {}),
        };
    }

    static hasFeature(config: SiteConfig, feature: keyof SiteConfig['features']): boolean {
        return !!(config.features && config.features[feature]);
    }

    static getContactInfo(config: SiteConfig) {
        return {
            email: config.contact?.email,
            whatsapp: config.contact?.whatsapp,
            socialMedia: config.socialMedia,
        };
    }

    static getWhatsAppLink(config: SiteConfig, message?: string): string {
        const whatsapp = config.contact?.whatsapp || '';
        const encodedMessage = message ? encodeURIComponent(message) : '';
        return `https://wa.me/${whatsapp.replace(/\D/g, '')}${encodedMessage ? `?text=${encodedMessage}` : ''}`;
    }
}
