"""
Nginx server block template generation for custom domains.
"""


def generate_nginx_server_block(domain, project_slug, platform_site_id="_saas"):
    """
    Gera um server block Nginx para um domínio customizado.

    Args:
        domain: str, hostname (ex: agenciafuturo.com.br)
        project_slug: str, project identifier (ex: agencia-marketing)
        platform_site_id: str, Astro site ID (default: _saas)

    Returns:
        str: Nginx server block configuration

    Raises:
        ValueError: if domain or project_slug contain invalid characters
    """
    import re

    # Validar domínio (RFC 1035 simplificado)
    if not re.match(r'^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$', domain):
        raise ValueError(f'Invalid domain: {domain}')

    # Validar project slug
    if not re.match(r'^[a-z0-9-]+$', project_slug):
        raise ValueError(f'Invalid project slug: {project_slug}')

    www_root = '/var/www'
    ssl_cert_path = f'/etc/letsencrypt/live/{domain}/fullchain.pem'
    ssl_key_path = f'/etc/letsencrypt/live/{domain}/privkey.pem'

    config = f"""# Nginx server block for {domain}
# Auto-generated by vitrine SaaS
# Project: {project_slug}
# Generated: {__import__('datetime').datetime.now().isoformat()}

# Redirect HTTP to HTTPS
server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    location /.well-known/acme-challenge/ {{
        root {www_root}/{platform_site_id}/{project_slug};
    }}

    location / {{
        return 301 https://$server_name$request_uri;
    }}
}}

# HTTPS server block
server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain} www.{domain};

    # SSL certificates (will be provisioned by Certbot)
    ssl_certificate {ssl_cert_path};
    ssl_certificate_key {ssl_key_path};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Document root for this project
    root {www_root}/{platform_site_id}/{project_slug}/current;
    index index.html;

    # Handle SPA routing: try file, then directory, then index.html
    location / {{
        try_files $uri $uri/ /index.html;
    }}

    # Cache static assets aggressively
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {{
        expires 1y;
        add_header Cache-Control "public, immutable";
    }}

    # Deny access to hidden files
    location ~ /\\. {{
        deny all;
        access_log off;
        log_not_found off;
    }}
}}
"""

    return config
