"""
Nginx server block template generation for custom domains.

Provisionamento em 2 fases (evita o problema "ovo e galinha" com SSL):
  1. generate_nginx_bootstrap_block(): só HTTP, sem `ssl_certificate` — pode
     ser escrito e recarregado com segurança porque não referencia nenhum
     arquivo de certificado (que ainda não existe). Serve o desafio ACME do
     Certbot e o próprio site em texto plano enquanto o certificado não sai.
  2. generate_nginx_full_block(): HTTP→HTTPS redirect + bloco HTTPS com SSL.
     Só deve ser escrito DEPOIS que o Certbot já emitiu o certificado —
     escrever isso antes faz `nginx -t` falhar (os arquivos de cert não
     existem ainda), derrubando o reload pra TODOS os domínios do host.

Convenções de path (ver docs/provisionamento-producao.md):
- Docroot: `{www_root}/{platform_site_id}/{project_slug}/current` — TODOS os
  projetos ficam aninhados sob 1 diretório pai (`platform_site_id`, ex:
  `_saas`), nunca soltos direto em `/var/www/{project_slug}`. Isso permite
  montar `/var/www/_saas` como 1 ÚNICO bind mount no container do Nginx,
  criado uma vez — sem isso, cada projeto novo do SaaS exigiria adicionar
  uma linha de volume no `docker-compose.yml` do Nginx e recriar o
  container (ver `create-vol.sh` do repo `reverse-proxy-config`), o que não
  escala pra um SaaS onde usuários criam projetos com frequência.
- ACME challenge: `/var/www/certbot` — path COMPARTILHADO entre todos os
  domínios do host (mesmo padrão já usado pelos sites legados, ver
  `reverse-proxy-config/sites/*.conf`), não um path por-projeto.
"""

import re
from datetime import datetime

_DOMAIN_RE = re.compile(
    r'^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
)
_PROJECT_SLUG_RE = re.compile(r'^[a-z0-9-]+$')

# Path compartilhado onde o Certbot grava os arquivos de desafio ACME,
# montado no container do Nginx (ver reverse-proxy-config/docker-compose.yml:
# "./certbot-challenges:/var/www/certbot"). Não depende de projeto/domínio.
ACME_CHALLENGE_ROOT = '/var/www/certbot'


def _validate(domain, project_slug):
    """Validação RFC 1035 simplificada — reaplicada no script restrito do
    VPS como defesa em profundidade (nunca confiar só na validação local)."""
    if not _DOMAIN_RE.match(domain):
        raise ValueError(f'Invalid domain: {domain}')
    if not _PROJECT_SLUG_RE.match(project_slug):
        raise ValueError(f'Invalid project slug: {project_slug}')


def _docroot(project_slug, www_root, platform_site_id):
    return f'{www_root}/{platform_site_id}/{project_slug}/current'


def generate_nginx_bootstrap_block(domain, project_slug, www_root='/var/www', platform_site_id='_saas'):
    """
    Config HTTP-only, sem nenhuma referência a certificado SSL.

    Use esta ANTES de rodar o Certbot. Serve o desafio ACME
    (`/.well-known/acme-challenge/`, path compartilhado `/var/www/certbot`)
    e o próprio site em HTTP simples — sem redirect pra HTTPS, porque ainda
    não existe HTTPS.

    Raises:
        ValueError: domain ou project_slug inválidos
    """
    _validate(domain, project_slug)
    docroot = _docroot(project_slug, www_root, platform_site_id)

    return f"""# Nginx bootstrap block for {domain} (HTTP-only, pré-SSL)
# Auto-generated by vitrine SaaS — Project: {project_slug}
# Generated: {datetime.now().isoformat()}
#
# Este bloco é substituído por generate_nginx_full_block() depois que o
# Certbot emitir o certificado. Não referencia ssl_certificate de propósito
# — escrever isso com certs inexistentes faz `nginx -t` falhar.

server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    location /.well-known/acme-challenge/ {{
        root {ACME_CHALLENGE_ROOT};
        try_files $uri =404;
    }}

    location / {{
        root {docroot};
        index index.html;
        try_files $uri $uri/ /index.html;
    }}
}}
"""


def generate_nginx_full_block(domain, project_slug, www_root='/var/www', platform_site_id='_saas'):
    """
    Config completa: redirect HTTP→HTTPS + bloco HTTPS com SSL.

    Só chame isso DEPOIS que o Certbot já emitiu o certificado pra este
    domain (arquivos em /etc/letsencrypt/live/{domain}/ precisam existir,
    senão `nginx -t` falha e o reload é abortado pelo script restrito).

    Raises:
        ValueError: domain ou project_slug inválidos
    """
    _validate(domain, project_slug)
    docroot = _docroot(project_slug, www_root, platform_site_id)
    ssl_cert_path = f'/etc/letsencrypt/live/{domain}/fullchain.pem'
    ssl_key_path = f'/etc/letsencrypt/live/{domain}/privkey.pem'

    return f"""# Nginx server block for {domain}
# Auto-generated by vitrine SaaS — Project: {project_slug}
# Generated: {datetime.now().isoformat()}

# Redirect HTTP to HTTPS (mantém o path do desafio ACME pra renovação futura)
server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    location /.well-known/acme-challenge/ {{
        root {ACME_CHALLENGE_ROOT};
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$server_name$request_uri;
    }}
}}

# HTTPS server block
server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain} www.{domain};

    ssl_certificate {ssl_cert_path};
    ssl_certificate_key {ssl_key_path};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    root {docroot};
    index index.html;

    location / {{
        try_files $uri $uri/ /index.html;
    }}

    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {{
        expires 1y;
        add_header Cache-Control "public, immutable";
    }}

    location ~ /\\. {{
        deny all;
        access_log off;
        log_not_found off;
    }}
}}
"""
