"""
Django settings for vitrine_core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-h(yw9jop06t!8kivq**6r6t!m5_=+pc6j@p=wyc9v*0kqtihqf',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['127.0.0.1', 'localhost', '0.0.0.0']

# Necessário pro login do admin funcionar atrás do proxy Nginx (POST de
# login é bloqueado por CSRF se a origin não estiver aqui, mesmo com
# ALLOWED_HOSTS correto). Precisa do scheme (https://) incluído.
CSRF_TRUSTED_ORIGINS = (
    os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if os.environ.get('CSRF_TRUSTED_ORIGINS') else []
)

# Nginx conversa com o Gunicorn via HTTP simples (proxy_pass http://vitrine:8000),
# mesmo quando o client original usa HTTPS — sem isso, Django não reconhece a
# conexão como segura (CSRF_COOKIE_SECURE, is_secure()) e pode gerar loop de
# redirect se SECURE_SSL_REDIRECT for ativado no futuro.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# @login_required (usado em core.views.preview_page) redireciona pra esta URL
# quando não autenticado — sem isso, cai no default /accounts/login/ que não
# existe neste projeto (só tem /admin/login/).
LOGIN_URL = '/admin/login/'


# Application definition

INSTALLED_APPS = [
    'core',
    'tenancy',

    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    *([] if not DEBUG else ['django_extensions']),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tenancy.middleware.CurrentClientMiddleware',
]

ROOT_URLCONF = 'vitrine_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vitrine_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# NAME fica em BASE_DIR / 'data' / 'db.sqlite3' (não direto em BASE_DIR)
# de propósito: em produção, docker-compose.yml monta um volume nomeado em
# /app/data — sem isso, o SQLite vive na camada gravável do container e
# some a cada `docker compose up --build` (rebuild recria o container do
# zero, perdendo todos os dados: projetos, usuários, builds).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Logging
# https://docs.djangoproject.com/en/5.1/topics/logging/
#
# Sem isso, o Django usa o handler padrão do 'django' logger, que só manda
# pro console quando DEBUG=True (filtro require_debug_true) — com
# DEBUG=False (produção), erros 500 não apareciam em lugar nenhum, nem no
# `docker logs vitrine`. Aqui forçamos log pro stdout sempre, independente
# de DEBUG, com o traceback completo — `docker logs vitrine` já captura
# stdout (driver json-file configurado no docker-compose.yml).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = os.environ.get('STATIC_URL', 'static/')
# Sem isso, `collectstatic` (rodado no run.sh do container) crasha com
# ImproperlyConfigured — precisa existir mesmo fora de produção.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.ClientUser'

# ============ SaaS Build & Deploy Settings ============

# Astro project root directory
ASTRO_ROOT = os.environ.get('ASTRO_ROOT', '/Users/edgar/Repos/fastvistos')

# Platform-wide Astro site ID (all user projects build together)
PLATFORM_SITE_ID = os.environ.get('PLATFORM_SITE_ID', '_saas')

# VPS deployment settings
VPS_PUBLIC_IP = os.environ.get('VPS_PUBLIC_IP', '72.60.57.150')
DEPLOY_SSH_HOST = os.environ.get('DEPLOY_SSH_HOST', 'localhost')
DEPLOY_SSH_USER = os.environ.get('DEPLOY_SSH_USER', 'deploybot')
DEPLOY_SSH_KEY_PATH = os.environ.get('DEPLOY_SSH_KEY_PATH', '/etc/vitrine/deploy_key')
WWW_ROOT = os.environ.get('WWW_ROOT', '/var/www')

# API security: shared secret for Astro build-time API calls
BUILD_API_SECRET = os.environ.get('BUILD_API_SECRET', '')

UNFOLD = {
    'SITE_HEADER': 'Vitrine Admin',
    'SITE_TITLE': 'Vitrine',
    'SITE_SYMBOL': 'settings',
    'SHOW_HISTORY': True,
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
    },
}
