import type { SiteConfig } from './lib/site-config-model.ts';

export const siteConfig: SiteConfig = {
    site: {
        business_id: '5810c2b6125c402a9cff53fcc9d61bf5',
        id: 'fake-site-id',
        domain: 'fakesite.com',
        canonical: 'https://p2digital.com.br/',
        name: 'Fake Site Name',
        description: 'This is a fake business description for the template.',
        language: 'en-US',
        useFullLanguageTag: true,
        currency: 'USD',
        timezone: 'America/New_York',
        logo: '/assets/images/logo-fake.png',
        primaryColor: '#FF5733',
        secondaryColor: '#3333FF',
        author: 'Fake Author',
        thumbnailUrl: '/assets/images/thumb-fake.jpg',
        image: 'https://fakesite.com/assets/images/logo/logo-footer.png',
        datePublished: '2025-01-01T00:00:00Z',
        dateModified: '2025-01-02T00:00:00Z',
    },
    contact: {
        email: 'contact@fakesite.com',
        whatsapp: '+1234567890',
    },
    socialMedia: {
        facebook: 'https://facebook.com/fakepage',
        twitter: '@faketwitter',
        instagram: 'https://instagram.com/fakeprofile',
        youtube: 'https://youtube.com/@fakechannel',
    },
    analytics: {
        gtmId: 'GTM-FAKE123',
    },
    verification: {
        googleSiteVerification: 'fake-google-site-verification',
    },
    features: {
        blog: true,
        booking: false,
        payments: true,
        multilingual: true,
    },
    customStyles: {
        cssVars: {
            '--accent-color': '#FAKE00',
        },
    },
    homePageConfig: {
        seo: {
            title: 'Fake Site Title',
            description: 'Fake site description for SEO.',
            keywords: ['fake', 'template', 'site'],
            themeColor: '#FF5733',
            msTileColor: '#FF5733',
            msTileConfig: '/browserconfig.xml',
            applicationName: 'Fake App',
            appleMobileWebAppCapable: 'yes',
            appleMobileWebAppStatusBarStyle: 'default',
            formatDetection: 'telephone=no',
            geoRegion: 'US',
            geoCountry: 'United States',
            geoPlacename: 'Fake City',
            openGraph: {
                type: 'website',
                locale: 'en_US',
                author: 'Fake Author',
                publishedTime: '2025-01-01T00:00:00Z',
                modifiedTime: '2025-01-02T00:00:00Z',
                section: 'Fake Section',
                tags: ['fake', 'template'],
                image: '/assets/images/og-fake.jpg',
                imageWidth: 1200,
                imageHeight: 630,
                imageType: 'image/jpeg',
                imageAlt: 'Fake OG Image',
            },
        },
    },
    blogPageConfig: {
        seo: {
            title: 'Fake Blog Title',
            description: 'Fake blog description.',
            keywords: ['blog', 'fake', 'template'],
            ogImage: '/assets/images/og-fake-blog.jpg',
            themeColor: '#FF5733',
            msTileColor: '#FF5733',
            msTileConfig: '/browserconfig.xml',
            applicationName: 'Fake App',
            appleMobileWebAppCapable: 'yes',
            appleMobileWebAppStatusBarStyle: 'default',
            formatDetection: 'telephone=no',
            geoRegion: 'US',
            geoCountry: 'United States',
            geoPlacename: 'Fake City',
            openGraph: {
                type: 'blog',
                locale: 'en_US',
                author: 'Fake Author',
                publishedTime: '2025-01-01T00:00:00Z',
                modifiedTime: '2025-01-02T00:00:00Z',
                section: 'Fake Blog Section',
                tags: ['blog', 'fake'],
                image: '/assets/images/og-fake-blog.jpg',
                imageWidth: 1200,
                imageHeight: 630,
                imageType: 'image/jpeg',
                imageAlt: 'Fake Blog OG Image',
            },
        },
        pagination: {
            postsPerPage: 5,
        },
    },
    blogPostConfig: {
        seo: {
            title: 'Fake Blog Post Title',
            description: 'Fake blog post description.',
            keywords: ['post', 'fake', 'template'],
            ogImage: '/assets/images/og-fake-post.jpg',
            themeColor: '#FF5733',
            msTileColor: '#FF5733',
            msTileConfig: '/browserconfig.xml',
            applicationName: 'Fake App',
            appleMobileWebAppCapable: 'yes',
            appleMobileWebAppStatusBarStyle: 'default',
            formatDetection: 'telephone=no',
            geoRegion: 'US',
            geoCountry: 'United States',
            geoPlacename: 'Fake City',
            openGraph: {
                type: 'article',
                locale: 'en_US',
                author: 'Fake Author',
                publishedTime: '2025-01-01T00:00:00Z',
                modifiedTime: '2025-01-02T00:00:00Z',
                section: 'Fake Article Section',
                tags: ['article', 'fake'],
                image: '/assets/images/og-fake-post.jpg',
                imageWidth: 1200,
                imageHeight: 630,
                imageType: 'image/jpeg',
                imageAlt: 'Fake Post OG Image',
            },
        },
        readingTime: true,
        showAuthor: true,
        relatedPosts: true,
    },
};
