/**
 * 🚨 AUTO-GENERATED FILE. DO NOT EDIT.
 * This file is generated by sync-blog.js and will be overwritten.
 * To customize, edit the template.
 */

import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';
import { siteConfig } from '../site-config.ts';
import { BlogService } from '../lib/blog-service.ts';
import { ensureTrailingSlash } from '../lib/utils.ts';

export const prerender = true;

// Gancho opcional por site: se existir `lib/llms-extra.ts` exportando
// `llmsExtraLines(canonical: string): string[]`, as linhas devolvidas entram no llms.txt
// logo depois da home (ex.: páginas de SEO programático do emprego). Site sem esse arquivo
// não muda nada: o glob devolve {} e o laço abaixo não roda.
const extraModules = import.meta.glob('../lib/llms-extra.ts', { eager: true }) as Record<
    string,
    { llmsExtraLines?: (canonical: string) => string[] }
>;

export const GET: APIRoute = async () => {
    const canonical = ensureTrailingSlash(siteConfig.site.canonical);
    const lines: string[] = [];

    lines.push(`# ${siteConfig.site.siteName}`);
    lines.push('');
    lines.push(`> ${siteConfig.homePageConfig.seo.description}`);
    lines.push('');
    lines.push('## Páginas');
    lines.push('');
    lines.push(`- [${siteConfig.site.siteName}](${canonical}): ${siteConfig.homePageConfig.seo.description}`);

    for (const mod of Object.values(extraModules)) {
        const extra = mod.llmsExtraLines?.(canonical) ?? [];
        if (extra.length > 0) {
            lines.push('');
            lines.push(...extra);
        }
    }

    if (siteConfig.features?.blog) {
        // Only list articles that also have a routable page: getStaticPaths()
        // in pages/blog/[...slug].astro builds pages from the content collection,
        // not directly from the database, so a published DB row without a
        // matching content/blog/*.md entry never gets a static page.
        const blogEntries = await getCollection('blog');
        const routableSlugs = new Set(blogEntries.map((entry) => entry.slug));

        const articles = await BlogService.getPublishedArticles();
        const routableArticles = articles.filter(
            (article) => article.slug && routableSlugs.has(article.slug)
        );

        if (routableArticles.length > 0) {
            lines.push('');
            lines.push('## Blog');
            lines.push('');

            for (const article of routableArticles) {
                const url = `${canonical}blog/${article.slug}/`;
                const description = article.seo_description || siteConfig.blogPageConfig?.seo?.description || '';
                lines.push(`- [${article.title}](${url})${description ? `: ${description}` : ''}`);
            }
        }
    }

    return new Response(lines.join('\n') + '\n', {
        headers: {
            'Content-Type': 'text/markdown; charset=utf-8',
        },
    });
};
