# Generated by Django 5.1.7 on 2026-07-21 13:00

import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_alter_client_managers_alter_clientprofile_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['client', 'role'], 'verbose_name': 'Perfil do Cliente', 'verbose_name_plural': 'Perfis dos Clientes'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['slug'], name='tenancy_cli_slug_a01b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_removed', 'created'], name='tenancy_cli_is_remo_0b3836_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['client', 'role'], name='tenancy_cli_client__08c60f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['is_removed', 'created'], name='tenancy_cli_is_remo_56440e_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('user',), name='unique_active_user_profile'),
        ),
    ]
